services:
  - type: web
    name: disaster-dashboard
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: '1'
